P13/urls.py
from django.contrib import admin
from django.urls import path,include
import myapp
from myapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('base/',views.base,name="Base"),
    path('',views.home,name="Home"),
    path('myapp/',include("myapp.urls")),
]

myapp/urls.py
from django.urls import path
from myapp import views
app_name="myapp"

urlpatterns = [
    path('trial/',views.trial,name="Trial"),
    path('profile/',views.profile,name="Profile"),
    path('get_demo/',views.get_demo,name="Get Demo"),
    path('post_demo/',views.post_demo,name="Post Demo"),
]

myapp/models.py
from django.db import models

# Create your models here.

myapp/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def trial(request):
    return HttpResponse("<h1> Project is on AIR </h1>")

def base(request):
    return render(request,"base.html")

def home(request):
    return render(request,"myapp/home.html")

def profile(request):
    name="Pyspiders"
    return render(request,"myapp/profile.html",{'name':name})

def get_demo(request):
    name=request.GET.get('name')
    return render(request,"get_demo.html",{'name':name})

def post_demo(request):
    if request.method=="POST":
        name=request.POST.get('name')
        return HttpResponse("<h1> Thanks for submission Mr./Mrs. {} </h1>".format(name))
    return render(request,"post_demo.html")

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %}
      <title>Base Html</title>
    {% endblock  %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-grid.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-grid.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-reboot.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-reboot.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script src="{% static 'js/bootstrap.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</head>
<body>
  {% include "partials/topbar.html" %}
  {% include "partials/navbar.html" %}

    {% block content %}
      <div class="container">
          <div class="jumbotron">
              <h1>Welcome to Base Page</h1>
              <img src="{% static 'images/django_logo.png' %}" alt="No img found" height="300" width="500">
          </div>
      </div>
    {% endblock  %}

    {% include "partials/footer.html" %}
</body>
</html>

templates/get_demo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Request | Get</title>
</head>
<body>
    <form method="GET">
        <label for="name">Name : </label>
        <input type="text" name="name" id="name">
        <input type="submit" value="submit">
    </form>
    <h1>{{name}}</h1>

</body>
</html>

templates/myapp/home.html
{% extends "base.html" %}

{% block title %}
  <title>Home Html</title>
{% endblock  %}

{% block content %}
  <div class="container">
      <div class="jumbotron">
          <h1>Welcome to Home Page</h1>
      </div>
  </div>
{% endblock  %}

templates/myapp/profile.html
{% extends "base.html" %}

{% block title %}
  <title>Profile Html</title>
{% endblock  %}

{% block content %}
  <div class="container">
      <div class="jumbotron">
          <h1>Welcome to {{name}} Profile Page</h1>
      </div>
  </div>
{% endblock  %}

templates/partials/footer.html
<!--Footer Html Page-->
<div class="alert alert-info" role="alert">
    <center>Footer</center>
</div>

templates/partials/navbar.html
<!--Nav Bar Html Page-->
<div class="container">
    <ul class="nav">
        <li class="nav-item">
            <a class="nav-link active" href="{% url 'Home' %}">Home</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'myapp:Profile' %}">Profile</a>
        </li>
    </ul>
</div>

templates/partials/topbar.html
<!--Top Bar Html Page-->
<div class="alert alert-secondary" role="alert">
    <center>Top Bar</center>
</div>

templates/post_demo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Request | Post</title>
</head>
<body>
    <form method="POST">
        {% csrf_token %}
        <label for="name">Name :</label>
        <input type="text" name="name" id="name">
        <input type="submit" value="submit">
    </form>
    
</body>
</html>